spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/domain_project
    username: domain_prod
    password: domain_prod
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  session:
    timeout: 30m
  output:
    ansi:
      enabled: detect
  #  security:
  #    user:
  #      name: "asdf1234"
  #      password: "lfsdjflksakdfjskdlfjsdkfjs21L"
  mvc:
    problemdetails:
      enabled: true
  #  ssl:
  #    bundle:
  #      pem:
  #        demo:
  #          reload-on-update: true
  #          keystore:
  #            certificate: "certs/certificate.crt"
  #            private-key: "certs/private.key"
  application:
    name: DnsManagement
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false
    clean-disabled: true

#server:
#  ssl:
#    bundle: "demo"
#  port: 443
#
#  error:
#    include-message: always
#    include-stacktrace: always
#    whitelabel:
#      enabled: false

logging:
  level:
    root: "info"
    org.springframework.web: "info"
    org.springframework.boot.web.embedded.tomcat.TomcatWebServer: "info"
    o.apache.tomcat.util.net.NioEndpoint.certificate: "info"
    org.hibernate: "info"
    bruzsal.dnsmanagement.service.interceptor: "debug"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
