@host = http://localhost:8080
@username = laszlo
@basicAuthHeader = Basic bGFzemxvOnBhc3N3b3Jk
@session_cookie = inic


###
GET {{host}}/api/records
Authorization: Basic d3Jvbmc6cGFzc3dvcmQ=

### add token
POST {{host}}/api/token?apiToken=oXY1Hivamz8zoYA73PGqBp5_kck58AfyQ_aFWCdU
Content-Type: application/json

### get token
GET {{host}}/api/token

